### PR TITLE
Fix bugs

### LINKED ISSUE #22: Add support for saving book details in Cosmos DB
* Add support for saving book information (JSON files) in Azure Cosmos DB.
* However, the image datastore will be on your file system.
  * The local image store would be found at: __System.getProperties("user.dir")/images__

For example, if I save a book: "James and the Giant Peach" by Ronald Dahl with a cover image "cover1.jpg". The JSON file stored in Cosmos DB will have something like:

```json
{
   "title": "James and the Giant Peach",
   "author": "Ronald Dahl",
   "cover": "/covers/dahl/ronald/cover.jpg"
}
```

And the image can be resolved from the local image store when I view a book.

### PR DESCRIPTION
**Pull request by Intern426**
Addressed the copy file issue and books are now saved properly
Fixed #22 
Added more tests to accompany the changes to save book

### CODE REVIEW

File: src/test/java/com/azure/app/LocalBookCollectorTest.java [hunk 1]
```diff
@@ -211,12 +212,14 @@ private void deleteJsonFile(Book book) {
                             book.getAuthor().getFirstName(),
                             new File(book.getCover()).getName()).toString()).delete();
                         deleteEmptyDirectories();
+                        delete = true;
```
Comment (conniey) [inline src/test/java/com/azure/app/LocalBookCollectorTest.java]: You can probably `break;` after being able to delete the book so you don't continue to iterate through all the books.

File: src/test/java/com/azure/app/LocalBookCollectorTest.java [hunk 2]
```diff
@@ -246,4 +249,72 @@ private void clearFiles(File[] files) {
...
+            new File(Paths.get(root, "Gingerbread.jpg").toString()).toURI());
+        //Act
+        localCollector.saveBook("James and the Giant Peach", new Author("Ronald", "Dahl"),
+            new File(Paths.get(root, "Wonder.png").toString()).toURI()).block();
+        result = localCollector.saveBook("James and the Giant Peach", new Author("Ronald", "Dahl"),
+            new File(Paths.get(root, "Gingerbread.jpg").toString()).toURI()).block();
+        files = Paths.get(root, "lib", "images").toFile().listFiles();
+        //Assert
+        Assert.assertTrue(result);
+        Assert.assertTrue(formerLength == files.length);
```
Comment (conniey) [inline src/test/java/com/azure/app/LocalBookCollectorTest.java]: `Assert.assertEquals(formerLength, files.Length);` would be a better method to call.
